### ISSUE TITLE
Remove from Blacklist

### ISSUE THREAD

**Issue by jdghenderson** [ZeroDot1/CoinBlockerLists#1]
Good Afternoon @ZeroDot1 

I just noticed that I am in your blackist (Coinminerz.com & 803mine.com), please can you remove my site as I don't have any browser mining in my code at all.

If you believe I do please can you let me know where so I can take action.

To confirm I am fully against mining code when viewing webpages and do not condone this kind of activity.

This request is following on from a post I saw for another browser blocker which referenced my site https://github.com/keraf/NoCoin/issues/68#issuecomment-338961883 

If you could help explain if I am wrong here that would be grand.

Thanks and have a great afternoon!

Kind Regards,

James

**Comment by ZeroDot1** [comment]
Sorry, my list is there to block mining completely. 
For this reason I cannot remove your domains.
The list is used to protect computers and networks from mining.

**Comment by jdghenderson** [comment]
Hi @ZeroDot1 many thanks for getting back to me. No worries makes perfect sense, I was concerned my site had malcious code that was mining when people viewed so glad to hear it is a general block.

I appreciate your response and good luck with your project as from what I can tell this things on the rise and it's not long until there are more variants of this code.

Thanks and have a great evneing!

Kind Regards,

James

**Comment by ZeroDot1** [comment]
I will create a list of optional addresses and add their domains there and remove them from the main list.

**Comment by jdghenderson** [comment]
Sounds like a good idea so then people can discern between the unwanted web mining code domains and clean pool sites. Cheers again!

**Comment by ZeroDot1** [comment]
Done! https://github.com/ZeroDot1/CoinBlockerLists/commit/7968cb26b55eeaf47bc585691dfab2e0ab978c14

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/6e55ba1b015577541cf466e187ba94a22bf336fc
