### ISSUE TITLE
Crypto mining on YouTube ads.

### ISSUE THREAD

**Issue by dnmTX** [ZeroDot1/CoinBlockerLists#100]
According to [https://arstechnica.com/information-technology/2018/01/now-even-youtube-serves-ads-with-cpu-draining-cryptocurrency-miners/?amp=1](url) it's a thing now.
@ZeroDot1  just something to look into,be prepared for the next wave i guess.

**Comment by ZeroDot1** [comment]
@dnmTX 
Thanks for the information, with the last two updates I added some URLs related to this topic.
I will keep watching. 
If you have URLs or addresses you want to block, just write them here.

**Comment by ZeroDot1** [comment]
https://blog.trendmicro.com/trendlabs-security-intelligence/malvertising-campaign-abuses-googles-doubleclick-to-deliver-cryptocurrency-miners/

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/commit/d9f6476f93c1af700937e87ee70614bcc56eb443
