### ISSUE TITLE
CoinPirate - Open Source In-Browser Javascript Web Miner

### ISSUE THREAD

**Issue by VriesHD** [ZeroDot1/CoinBlockerLists#101]
Mines XMR & ETN

Domain:
`coinpirate.cf`

IP:
`46.101.160.153`

**Comment by ZeroDot1** [comment]
@VriesHD Thanks for the information.

**Comment by ZeroDot1** [comment]
@VriesHD 
Thank you, the URL, and the address are included in the next update of the CoinBlockerLists.

**Comment by ZeroDot1** [comment]
@VriesHD 
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/d9f6476f93c1af700937e87ee70614bcc56eb443
