### ISSUE TITLE
NFWebMiner, Mining.Best, Webcoin, WebXMR, Sparechange

### ISSUE THREAD

**Issue by VriesHD** [ZeroDot1/CoinBlockerLists#102]
NFWebMiner: Monero WebAssembly Miner
---------------------------------------------
Domain: nfwebminer.com
IP: 130.255.76.80
JS: https://nfwebminer.com/lib/miner.js
Default Minername: NFMiner
Proxy/other: 
8000plus.si - 84.255.204.158 - 8000plus.si/lib/miner.js

mining.Best: Monero JavaScript Mining Service
-------------------------------------------------
Domain: mining.best - xmr.mining.best
IP: Behind cloudflare 104.27.152.208-104.27.153.208
JS: https://xmr.mining.best/xmr-1.2.js
Default Minername: miningBest.Go

WebCoin: Cryptonote Miner for Karbo
------------------------------------------
Domain: krb.devphp.org.ua
IP: 185.68.16.36
JS: http://krb.devphp.org.ua/webcoin.min.js
Default Minername: WebCoin.Miner

WebXMR: The fastest cryptocurrency webminer for your Website (Beta)
-------------------------------------------------------------------------
Domain: webxmr.com
IP: 46.4.154.10
JS: https://webxmr.com/miner.js(old) and https://webxmr.com/webxmr.js
Default Minername: Miner(old) and webxmr

Sparechange.io: A browser based crypto currency miner
------------------------------------------------------------
Domain: sparechange.io
IP: 35.160.145.252
JS: https://www.sparechange.io/static/sparechange.js
Default Minername: Miner
WordPress-plugin: https://wordpress.org/plugins/sparechange/

**Comment by ZeroDot1** [comment]
@VriesHD Thank you very much for all the information, I will include it in the next update.

**Comment by ZeroDot1** [comment]
@VriesHD  Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/258e5017d8160fdb26ea8f55e9d83f61994a3f37
