### ISSUE TITLE
Possible Bypass?

### ISSUE THREAD

**Issue by BakaTekku** [ZeroDot1/CoinBlockerLists#104]
[Miner](https://pste.eu/p/9OQq.html) This one seems to use `cdn.minescripts.info`

**Comment by ZeroDot1** [comment]
@BakaTekku Thanks for the information, I will add it with the next update.

**Comment by ZeroDot1** [comment]
@BakaTekku 
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/ce9b814e7ef10cb294a35aa9a5b348d2c7d55211
