### ISSUE TITLE
New domains to block

### ISSUE THREAD

**Issue by xd4rker** [ZeroDot1/CoinBlockerLists#107]
Here are some few domains that should get blocked

`cfcnet.gdn`
`cfcs1.duckdns.org`

source: https://tainies.online & http://d.cfcnet.gdn/d.php?w=lol

`freecontent.stream`

source: https://www.coinimp.com/documentation

**Comment by ZeroDot1** [comment]
Thank you very much for the information, I will make an update as soon as I can.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/a68c903d41f6bf29b0e9ebb1d62391a452decf65
