### ISSUE TITLE
Thank you - feeds are now in MISP

### ISSUE THREAD

**Issue by adulau** [ZeroDot1/CoinBlockerLists#108]
FYI, we added the CoinBlockerLists in the default feed of [MISP](https://github.com/MISP/MISP/commit/4b30ca63049206ec3b7951baec33ac33f25c56fe).

**Comment by ZeroDot1** [comment]
Many thanks, with the next update I will add it to the Readme.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/57aaadb666bea03e1c53bb2c39bc8b4bdcf71ac3
