### ISSUE TITLE
New domains to block

### ISSUE THREAD

**Issue by xd4rker** [ZeroDot1/CoinBlockerLists#110]
These domains where recently added to MinerBlock

`cfcnet.top`
source: http://d.cfcnet.gdn/d.php?w=lol

`graftpool.ovh`
source: https://www.2giga.link/
https://graftpool.ovh/car.js

**Comment by ZeroDot1** [comment]
Thank you very much for the information, I will make an update right now.

**Comment by ZeroDot1** [comment]
@xd4rker Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/0a901e67715b008b7e2851f8ea2e9ba629ab6dec
