### ISSUE TITLE
What does rawgit.com have to do with CoinBlockers?

### ISSUE THREAD

**Issue by mazesy** [ZeroDot1/CoinBlockerLists#111]
Two CoinBlockerLists include `rawgit.com`,
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

Would you please consider removing this `rawgit.com` from thse two lists?

Thanks.

**Comment by ZeroDot1** [comment]
@mazesy Thanks for the information, the next update will solve the problem.

**Comment by ZeroDot1** [comment]
@mazesy I apologize for the mistake, thanks again for reporting it.

**Comment by ZeroDot1** [comment]
@mazesy Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/256aa34e699b3c7ee34007586d61edff8ef021c1

**Comment by mazesy** [comment]
It's back. **_rawgit.com_** appears again in latest [list_browser.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt)

I don't know where you get your sources from but **_rawgit.com_** **never has had and has not the slightest relation with bitcoins.** -- How can it ever appear on your lists?

This is over for me. Too many mistakes, repeated moreover. Unreliable.

Good luck.
