### ISSUE TITLE
s3.amazonaws.com is in blacklist

### ISSUE THREAD

**Issue by jnishi121** [ZeroDot1/CoinBlockerLists#112]
Amazon's S3 URL is being blocked by this list as of the latest version. I hope this is a mistake?

**Comment by ZeroDot1** [comment]
@jnishi121 Thank you very much for the information, the bug is fixed.
https://github.com/ZeroDot1/CoinBlockerLists/commit/d5aa1e147c6d8ce1f5ed9de91908e30b76fc8c9b 
I'm working without glasses right now because it broke.
I just didn't see it, sorry.

**Comment by jnishi121** [comment]
Thanks for the quick fix!
