### ISSUE TITLE
PopAds.net DGA webmining servers.

### ISSUE THREAD

**Issue by VriesHD** [ZeroDot1/CoinBlockerLists#114]
I know they're currently still using CoinHive, but considering their domains seem to reach Alexa top500 ratings: https://twitter.com/360Netlab/status/965641732057649152

It might be an idea to block just to be sure(just in case they decide to ditch the DGA and go local)
- 216.21.13.10 
- 216.21.13.11 
- 216.21.13.12 
- 216.21.13.13 
- 216.21.13.14
- 216.21.13.15
- 216.21.13.16
- 216.21.13.17

**Comment by ZeroDot1** [comment]
@VriesHD Thanks for the information, I add the IPs to the list.

**Comment by ZeroDot1** [comment]
@VriesHD Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/06f7282b7c1b9963ba1f8175cce86f4e12337e3f
