### ISSUE TITLE
joyreactor.cc

### ISSUE THREAD

**Issue by hant0508** [ZeroDot1/CoinBlockerLists#115]
Joyreactor is a popular in Russian Internet website with memes and user-generated content (something like 9GAG). Blocking `joyreactor.cc` completely breaks the website with all subdomains.

**Comment by ZeroDot1** [comment]
@hant0508 The next update fixes the problem, thanks for the information.

**Comment by ZeroDot1** [comment]
@hant0508 Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/bd461930b7a2fa4a72b1b7d840f8849b6a96a900
