### ISSUE TITLE
Possible miner !!!

### ISSUE THREAD

**Issue by dnmTX** [ZeroDot1/CoinBlockerLists#116]
@ZeroDot1  i couldn't find it but just by opening the link my CPU went up to 65% and stayed there untill i closed the page.Maybe you could have better luck but i'm 95% sure that there is a miner there.
http://vidto.me/uzpm2sd2g218.html     (wait for the countdown and click proceed to video  to get to the right page)

**Comment by ZeroDot1** [comment]
@dnmTX Thank you very much for the information, I will take a look at it and update the lists.  
 If it is possible that in the future you can copy the source code of the page and send it to me via Ghostbin [https://ghostbin.com], for example, that would make my work easier. 
https://ghostbin.com/paste/g3ukd

**Comment by dnmTX** [comment]
@ZeroDot1  i'll do my best(sorry....kind of a noob here),just trying to help with my limited knowledge but i'm learning though.Let me know how it goes with this one,kind of curious,and if you find something maybe  you can post some reproduction steps on how to so i'll know for the future.

**Comment by ZeroDot1** [comment]
@dnmTX A miner has been found on the page you specified, the next update fixes the problem, thanks for the information. 

```
m1.videos.vidto.me
m2.videos.vidto.me
```

**Comment by ZeroDot1** [comment]
@dnmTX Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/2254e733bfbd6aa4b3987998d67d2d252ac9a26c

**Comment by dnmTX** [comment]
@ZeroDot1 
![gift](https://user-images.githubusercontent.com/34774426/36639126-de41c63c-19ca-11e8-87b2-f6fb1a92d009.PNG)

ENJOY Brother :-)

**Comment by ZeroDot1** [comment]
@dnmTX  Thank you very much for the donation, it helps me so much.
With the cooler I now also have the possibility to work better in summer, now I don't have to switch off the computer during the day and can therefore work more efficiently in summer.
Thank you very much.

**Comment by dnmTX** [comment]
@ZeroDot1  no thanks necessary,just a small gesture of appreciation for the work you doing.Sorry i couldn't do more but the finances are tight here at the moment.Enjoy your gift.
P.S. Let me know if there are any problems with the delivery....hope not....

**Comment by ZeroDot1** [comment]
@dnmTX I posted a picture on twitter, https://twitter.com/hobbygrafix/status/968910377210859526
Thank you for the donation. The cooler works very good.

**Comment by dnmTX** [comment]
@ZeroDot1  twitter is blocked here so i can't see the picture(no biggie),as long as it's working as intended and you like it the rest it's not important. Enjoy it man,you deserve it.

**Comment by ZeroDot1** [comment]
Thank you very much.

**Comment by ZeroDot1** [comment]
@dnmTX Try it with another DNS server, maybe you can open twitter. 
Here is a list of DNS servers: https://github.com/ZeroDot1/Bash_my_little_collection/blob/master/Bash_Tool/readme.md
