### ISSUE TITLE
Bootstrap false positives

### ISSUE THREAD

**Issue by ronaldmexico** [ZeroDot1/CoinBlockerLists#118]
Below IP's in the list appear to be false positives.  Saw lots of traffic in our network and multiple page load issues as a result of them being blocked.  

Example site -> https://mxtoolbox.com/

https://www.virustotal.com/en/ip-address/94.31.29.16/information/
https://www.virustotal.com/en/ip-address/108.161.189.121/information/

**Comment by ZeroDot1** [comment]
@ronaldmexico The problem is fixed: https://github.com/ZeroDot1/CoinBlockerLists/commit/c0692d7c24609b2bd97b1b550a1627d91e2b678d 
The IPs were listed because until a few days ago there was still malware to be found.
Thank you for reporting the problem.
