### ISSUE TITLE
Suggestion : a unique list combining all three available

### ISSUE THREAD

**Issue by mazesy** [ZeroDot1/CoinBlockerLists#121]
Hi,

There are 3 available lists at this time:

```
list.txt
list_browser.txt
list_optional.txt
```

For users who update once a day all these 3 lists, having a unique list (say, _list_all.txt_) combining them all would be welcomed.

Thanks

**Comment by ZeroDot1** [comment]
@mazesy A list of all lists is planned, I will create it as soon as possible.

**Comment by ZeroDot1** [comment]
@mazesy When do you need the combined list?
