### ISSUE TITLE
rawgit.com, again, on a Coinblocker list.

### ISSUE THREAD

**Issue by mazesy** [ZeroDot1/CoinBlockerLists#122]
It's back. rawgit.com appears again in latest list_browser.txt

I don't know where you get your sources from but rawgit.com never has had and has not the slightest relation with bitcoins. -- How can it ever appear on your lists?

This is over for me. Too many mistakes, repeated moreover. Unreliable.

Good luck.

**Comment by ZeroDot1** [comment]
@mazesy Sorry, it happened when I merged the update, I'm correcting that and putting it on the white list.

**Comment by ZeroDot1** [comment]
@mazesy Thank you for the information. Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/b1ddf96e02d81915bff4eb0dcc463b56c9fd4442

**Comment by ZeroDot1** [comment]
@mazesy I know it's a bad mistake, I hope it doesn't happen anymore, I'm sorry.
