### ISSUE TITLE
Add cfcnet.top URLs

### ISSUE THREAD

**Issue by ZeroDot1** [ZeroDot1/CoinBlockerLists#123]
### Description:
https://urlscan.io/result/f3d96f67-1fe2-43e7-a549-5110bc55a053#iocs

### URL and IPlists:

```
as.cfcnet.top
d.cfcnet.top
eu.cfcnet.top
us.cfcnet.top
vip.cfcnet.top
cfcnet.top
```

### Additional Information:
Found With Google.

**Comment by dnmTX** [comment]
@StevenBlack @ScriptTiger can you guys update your lists so i can get the latest update from here.Thanks
@ZeroDot1  Thank you !!!!

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/620210b13ae1e28f4c7b7aa0d614dfeae45ef1bd

**Comment by StevenBlack** [comment]
Done!  https://github.com/StevenBlack/hosts/commit/37da299efb31a589e37db092abb805d759b477c3

**Comment by dnmTX** [comment]
Just following up on this one(due to importance and to spread awareness).GOOGLE main page was affected big times.I was wondering why when i open it my CPU was ramping up to 10%-15% every time,most likely those GIF animations were compromised.After updating my hosts file all went back to normal and no animations as well. @ZeroDot1  GOOD JOB my friend.....GOOD JOB !!!!!
###Example of another victim(who knows how many they are out there)
https://www.techpowerup.com/forums/threads/browser-hijack-gpu-15-when-using-google-in-ff.242004/

**Comment by ScriptTiger** [comment]
I use DuckDuckGo.com as my default search engine, and also use their plug-in for Chrome.

**Comment by dnmTX** [comment]
Thanks @ScriptTiger  i'll give it a shot

**Comment by ZeroDot1** [comment]
@dnmTX @ScriptTiger 
I am using Google, I have set up this start page in my browser, it is very helpful. The search field has been adjusted so that no entries can be recorded.
If you search through this page, only results in the selected language will be displayed. 
https://mikelpint.github.io/Startpage/de.html
The English version of the site is not up to date, but anyone who wants to can contribute to the project. 
https://github.com/mikelpint/Startpage

**Comment by ScriptTiger** [comment]
You should be able to use the same parameters from that project to set up a custom search engine string, as well.

Chrome->Settings->Manage search engines

https://encrypted.google.com/search?ie=UTF-8&oe=UTF-8&lr=lang_en&sitesearch=&q=%s&GButton.x=0&GButton.y=0

Where "%s" expands to your search string that you type into the location bar and is sent to your default search engine.

**Comment by ZeroDot1** [comment]
The CSS doesn't work correctly in Firefox.
The source text of the search box:
```html
<div class="text-center search-query fonts bg">
    <div class="search-box bg fonts">
      <form action="https://encrypted.google.com/search" method="get">
        <input type=hidden name=ie value=UTF-8>
        <input type=hidden name=oe value=UTF-8>
        <input type="hidden" name="lr" value="lang_de" />
        <input type="hidden" name="sitesearch" />
        <input required="required" autocomplete="off" autofocus readonly onfocus="this.removeAttribute('readonly');" type="text" name="q" placeholder="Websuche mit Google" class="search-query" />
        <input type=image name=GButton src="imgs/google.png" class="dropbtn" style="border-radius: 5px; filter: grayscale(100%); width: 55px; height: 55px; margin-left: 10px; vertical-align: middle;">
        <!-- Note: The autofocus attribute of the input tag is not supported in Internet Explorer 9 and earlier versions. -->
      </form>
    </div>
  </div>
```

**Comment by ScriptTiger** [comment]
Can you make custom search engines in Firefox? I know there's also startpage.com and they have a Firefox add-on:
https://addons.mozilla.org/en-US/firefox/addon/startpage-https-privacy-search/?src=search

But I personally don't use it, so I can't recommend it.

**Comment by ZeroDot1** [comment]
@ScriptTiger Yes, I can make a new project with a customized CSS, so it works fine.

**Comment by ZeroDot1** [comment]
@ScriptTiger https://github.com/ZeroDot1/CBStartpage 
I invited her to the project. As soon as I can, I'll upload the first version of the page, but it will take some time, because I have to rebuild everything.

**Comment by ScriptTiger** [comment]
Don't you have write access to the original project?

**Comment by ZeroDot1** [comment]
I have write access to the project, but I find it better to write an extra page especially for Firefox users.

**Comment by ScriptTiger** [comment]
Maybe after the Firefox pages are perfected and tested they can be merged using browser detection to load the browser-specific form with something like jQuery. Then there can just be a "browsers" directory with the different browser form snippets, like browsers/firefox.html, browsers/chrome.html, and they can just be loaded/imported into each language file. It would make managing the languages and managing the browser forms a lot easier. There could also be a drop-down to select browser, since browser detection isn't always reliable.

**Comment by dnmTX** [comment]
@ZeroDot1 any chance to get Startpage with search field ONLY(in the middle) connected to google(the logo is nice) and on english ONLY,same font ,nothing else?

**Comment by ZeroDot1** [comment]
@dnmTX I write an extra page for you and host it in a subfolder.

**Comment by dnmTX** [comment]
@ZeroDot1 thanks man.If it's too much work,leave it for when you can,no rush.

**Comment by ZeroDot1** [comment]
@dnmTX The base is already finished, I just have to adjust something, which background color you want to have.  
![bildschirmfoto_2018-03-02_21-39-23](https://user-images.githubusercontent.com/28985171/36920885-8203c2ca-1e62-11e8-803d-5002f316ec3a.png)

**Comment by ZeroDot1** [comment]
@dnmTX 
![bildschirmfoto_2018-03-02_21-43-02](https://user-images.githubusercontent.com/28985171/36920944-baa559e0-1e62-11e8-845e-4ff6ecf41834.png)

**Comment by dnmTX** [comment]
@ZeroDot1  the grey one(like the original one). Maybe longer search field and smaller logo?

**Comment by ZeroDot1** [comment]
No problem, I'll finish it.

**Comment by dnmTX** [comment]
Wow...you...are...fast

**Comment by dnmTX** [comment]
Another question,i'm using chromium and have search option in the context menu,is there a way to link it to the same page?

**Comment by ZeroDot1** [comment]
@dnmTX I see only 1%, I have to be faster than normal people, otherwise I can't keep up.  
I haven't figured out how to set up another default search engine yet.

**Comment by dnmTX** [comment]
Got it,and again,no rush on that at all,i'm pretty sure you have better things to do.You'll let me know down the road when you figure something for the search engine.Thanks again.

**Comment by ScriptTiger** [comment]
I think adding default search engines in Firefox requires add-ons. Those packages are pretty small though, so it's definitely something that can be looked into later on after the startpage is perfected.

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2018-03-02_22-08-17](https://user-images.githubusercontent.com/28985171/36921890-44d63e56-1e66-11e8-82bc-610b9717c956.png)

**Comment by ZeroDot1** [comment]
@dnmTX @ScriptTiger https://zerodot1.github.io/CBStartpage/dnmTX_Page/index.html
The page is ready, please test it.

**Comment by dnmTX** [comment]
@ZeroDot1  Feedback:  when i search something it showing me german results (!) .Maybe longer search field(with no comments inside...or just Google is fine).You can remove the bottom field(Created by...)...no offense though....i just like as simple as possible.Search field lenght same as the google main page(if possible...of course)
About your main project,i saw you and ScriptTiger were discussing the language support.I can help with Bulgarian if need to.(Just FYI)

**Comment by ZeroDot1** [comment]
Done : https://github.com/ZeroDot1/CBStartpage/commit/4ad11c2ae3ea29f4d91e56bfc386bd7911c4e084

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2018-03-02_22-56-12](https://user-images.githubusercontent.com/28985171/36923887-fff0c322-1e6c-11e8-9b33-10be53448f3c.png)

**Comment by dnmTX** [comment]
@ZeroDot1  can you change the  placeholder="Web Search with Google"  to  placeholder="Google"  make the search field longer? So far....loving it...
### Example.......Ok something went wrong...this is what i got:
![screenshot 6](https://user-images.githubusercontent.com/34774426/36924072-e4522f14-1e32-11e8-8fe8-85962a83e4cc.png)
...when i click on the page it get's aligned but when i open the page this is what i see....

**Comment by ZeroDot1** [comment]
@dnmTX Done. 
I hope it's ok if you want to change something else, feel free to do so, because I invited you to the project.
Hm, that's a problem with smaller resolutions.
