### ISSUE TITLE
false positive supportxmr.com

### ISSUE THREAD

**Issue by M5M400** [ZeroDot1/CoinBlockerLists#124]
### Description:

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt lists 

```
pool-de.supportxmr.com
pool.supportxmr.com
supportxmr.com
```
It is a legit cryptocoin mining pool, there are no ads on the page and no webmining scripts (I despise this webmining cancer; my pool even has a policy against it).

While I do understand why it has been added, it causes me much additional support effort, since my regular miners suddenly have connection problems with both their legit monero miners, and the website/API itself.

Is there a way to better deal with this?

**Comment by ZeroDot1** [comment]
@M5M400 There is no way to remove these URLs from the list.
Take a look here: https://github.com/ZeroDot1/CoinBlockerLists/issues/119#issuecomment-368872883
I'm sorry there are many problems with this, but these lists are designed to protect users from cryptojacking and similar attacks.
