### ISSUE TITLE
CoinBlockerList for browser title

### ISSUE THREAD

**Issue by happysurf** [ZeroDot1/CoinBlockerLists#125]
### Description:

The CoinBlockerList for browser don't have title in Ublock Origin filter list.

### Steps To Reproduce:

1. Load the CoinBlockerList for browser in Ublock Origin;
2. Go to Options > 3rd-party filters tab;
3. In the > Custom filters appear as title the entire link: https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

### Expected Behavior:
Will be great have a title for the filter list.

**Comment by superlex** [comment]
I agree.
Some information is missing, e.g.:
```
! Title: 
! Description: 
! Version: 
! Expires: 
! Homepage: 
! License: 
```
Thank you for your list ZeroDot1.

**Comment by ZeroDot1** [comment]
@superlex @happysurf With the last update I added an extra list for UBlock. 
Please test it and let me know if there is a bug. 
 
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser_UBO.txt

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2018-03-13_18-24-31](https://user-images.githubusercontent.com/28985171/37358620-d3241984-26eb-11e8-8b12-f2b9f8debbba.png)

**Comment by ZeroDot1** [comment]
@superlex Sorry I deleted your comment, it was a mistake.
I agree.
Some information is missing, e.g.:

! Title: 
! Description: 
! Version: 
! Expires: 
! Homepage: 
! License: 
Thank you for your list ZeroDot1.

**Comment by happysurf** [comment]
Thank you very much, I want suggest your CoinBlockerList to UBO developer for add in the 3rd-party filters default pack.

**Comment by ZeroDot1** [comment]
@happysurf Thank you very much :) That's a good idea.

**Comment by superlex** [comment]
@ZeroDot1 
Thanks for the new specific list :)
I think there is no problem as regards sorting.

**Comment by ZeroDot1** [comment]
@happysurf @superlex https://github.com/gorhill/uBlock/issues/3600
