### ISSUE TITLE
[Info] Referencement

### ISSUE THREAD

**Issue by funilrys** [ZeroDot1/CoinBlockerLists#126]
Hello @ZeroDot1 ,

You may have already been informed but as the structure changed I still share the following for archiving. 

Because I want to be transparent, I just wanted to inform you that we added `list.txt` to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists](https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists).

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by ZeroDot1** [comment]
@funilrys Thank you for the information, and thank you for using the CoinBlockerLists. 
I hope this is good stuff for your online security.

**Comment by dnmTX** [comment]
@ZeroDot1.  @funilrys  is part of  @SevenBlack's team for managing the Unified hosts.Just FYI. 😉
