### ISSUE TITLE
CoinBlockerList for uBlock: possible improvements

### ISSUE THREAD

**Issue by superlex** [ZeroDot1/CoinBlockerLists#127]
Ok, I want to summarise how ublock specific list could be improved according to #3600:
- use ublock syntax ||domain^ [ gorhill ]
- remove redundant domains (eg. a1.domain and a2.domain with ||domain^) [ gorhill ]
- block specific script instead of full domain [ uBlock-user ]

**Comment by dnmTX** [comment]
I was wondering this myself how the list would work in adblocker without "||" "^" characters among others. Didn't want to comment on this earlier due to not using uBlock personally but looks like they all share the same characters anyway,@ZeroDot1 you can refer to this repo just get a hint if you planing to do some improvements.
https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt

**Comment by ZeroDot1** [comment]
@superlex @dnmTX 
I'll take a close look at all this and test it for about two weeks. If anything needs to be changed, I'll do it as soon as I can.

**Comment by superlex** [comment]
@ZeroDot1 
Thank you :)

**Comment by dnmTX** [comment]
@superlex  meanwhile if you're on Windows you can use HostMan (http://www.abelhadigital.com/hostsman/) and load the @ZeroDot1  list in your hosts file which is the better option as a first line of defense at least for me.

**Comment by superlex** [comment]
Thanks for your suggestion @dnmTX, take a look of this too:
https://github.com/StevenBlack/hosts
It includes CoinBlocker :)

**Comment by ZeroDot1** [comment]
@dnmTX @superlex OK, I have tested the list for UBO, and I have come to the conclusion that it is sufficient as I have done it. Every user is able to put certain things that the user wants on the white list.

**Comment by dnmTX** [comment]
I was just expressing opinion(not a uBlock user here) as for me as i stated earlier i count more on my hosts file to protect me rather then the adblocker. Still,it's good to have alternatives as i'm sure many uBlock users will appreciate your hard work.

**Comment by superlex** [comment]
Ok @ZeroDot1 , 
thanks :)
