### ISSUE TITLE
cryptaloot.pro, a variety of cryptoloot.pro

### ISSUE THREAD

**Issue by bluesky139** [ZeroDot1/CoinBlockerLists#128]
I notice cryptoloot.pro is already added in list, please treat cryptaloot.pro as same way.
Full url is `https://cryptaloot.pro/lib/cry.wasm`
Both these domains are redirect to `https://crypto-loot.com/`

**Comment by ZeroDot1** [comment]
@bluesky139 Thanks for the information, I will add the missing entries as soon as I can.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/ae78e6b67647e1b2b1f7a289dd5eb93a08d5b6ce
