### ISSUE TITLE
Wrong url included?

### ISSUE THREAD

**Issue by An-dz** [ZeroDot1/CoinBlockerLists#133]
### Description:

I noticed that `goodolddownloads.com` is listed here and this seems wrong. The front page doesn't even have JavaScript. And I don't see any spike in CPU.

### Log Files and Pages Source code:

[Front page HTML](https://privatebin.net/?7f7c10f6d7323112#ZD27j4g2n5Ji6R3GoTm4himbfplldeXw/jjjODqplsE=)

[Scene page HTML](https://privatebin.net/?87a5199e3df73b73#5Awr9jXVk3AuPci4s0kR8g44uE99PJkSMXeP/OV4FbQ=)
[Scene page JS1](https://privatebin.net/?5ea6e40ee6c49a48#OenYQyIROVDk0l1UO5dg2x+kob6akt6NEZZKUz4SE7Q=)
[Scene page JS2](https://privatebin.net/?b14118bf364b1598#1EKrhJm363sSkkQzxWchkLPm0ZIGwXJs0Gqtuxp6yNY=)
[Scene page JS3](https://privatebin.net/?4fcf51ade78711ca#LRQ5+Ie2l6SPywBijGqXnLqHK2+B4E1z9jl810SqMpo=)

[GOG page HTML](https://privatebin.net/?e04ec0c7741faffc#cDE1CSsbB04w++38ehK7K5lECx+NJmDr1VcbSbn2PUc=)
[GOG page JS1](https://privatebin.net/?3e4016bd383cff2e#eNnB277/Urt0mKu3OfwiEfloWF/RAFDU9uGs0kFpfhc=)
[GOG page JS2](https://privatebin.net/?02a37bb2222d90cb#FfVmBsTVV4asLR0mInGStmxiwnsfWwbjeNzq5yGlvus=)

### URL and IPlists:

```
goodolddownloads.com
scenegames.goodolddownloads.com
goggames.goodolddownloads.com
```

**Comment by ZeroDot1** [comment]
@An-dz I'll check as soon as I can.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/728181d4e2b2510da5ae674efe8861c4d643723e
