### ISSUE TITLE
Ad company that uses cryptominers

### ISSUE THREAD

**Issue by An-dz** [ZeroDot1/CoinBlockerLists#134]
### Description:

I've found a Brazilian ad network that employs cryptominers with their ads.

### Steps To Reproduce:

1. Open the site https://www.naointendo.com.br/ on a Windows machine with Windows Defender. (like Windows 10)
2. Windows Defender shows up saying it blocked a cryptominer
3. Or you can just notice the spike in CPU in another OS

### Log Files and Pages Source code:

Inside the head of NaoIntendo there's this script:

`<script id="boost-box" async="" src="https://banner.boostbox.com.br/integrations/script.js?token=8ad3094d75acfd1a5e78cffe"></script>`

The source code of said script: [Script 1](https://privatebin.net/?14a12e3d87e0fb29#ziiGf2F+9+E+s+KcwU/aXaXMcxpGOgiOu5UgPnbM0ZM=)

At line 49 you notice there's a call to the function at the beginning of the document, which creates a frame. The url of this frame is `//banner.boostbox.com.br/banners/8ad3094d75acfd1a5e78cffe` as is in line 49.

[Frame 1 source](https://privatebin.net/?cd59cd9f1560d65a#kUWUGWerKxkfKWZeqEfEfpq1K1Jx/NlAYzX2TG9AAPw=)

This frame is the one that apparently runs a cryptominer as blocking it keeps the CPU at rest and doesn't make Windows Defender alert on the Windows 10 machine.

### URL and IPlists:

The following should be added:

```
boostbox.com.br (some scripts load from here)
www.boostbox.com.br (some scripts load from here)
banner.boostbox.com.br (frames that add the miners scripts)
```

**Comment by ZeroDot1** [comment]
A list of all SubURLs I could find.
```bash
www.boostbox.com.br
banner.boostbox.com.br
www.banner.boostbox.com.br
blog.boostbox.com.br
imgn.boostbox.com.br
mail.boostbox.com.br
```

**Comment by An-dz** [comment]
Thanks for the quick reply. I just want to help others not fall for those.

**Comment by ZeroDot1** [comment]
The update is ready, it will be uploaded at 00:01 o'clock.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/9e37d9ce74ca6aa9581d01d8110cd1cdc5e74146
