### ISSUE TITLE
Invalid hosts

### ISSUE THREAD

**Issue by shdyy** [ZeroDot1/CoinBlockerLists#135]
- Remove kickass.cd
uses mine.torrent.pw

- Remove estream.to
uses m1.streaming.estream.to m2.streaming.estream.to

I will add here if I find more

**Comment by shdyy** [comment]
I'm not convinced these are miner hosts themselves, which I noticed on Anti-WebMiner and also included here. I'm sure there are many more

2giga.dowload (which has a typo)
2giga.link

rapidvideo.com

safelinkconverter.com

shrink-service.it

vidfile.net

vidzi.tv

**Comment by shdyy** [comment]
Update: estream.to now also use

play.video.estream.nu

s2.video.estream.nu
s3.video.estream.nu

**Comment by ZeroDot1** [comment]
@shdyy Thank you for your contributions, I'll take a close look and I' ll make an update as soon as possible.

**Comment by shdyy** [comment]
Some software may not support it, but you can alternatively use 0 instead of 0.0.0.0 to make the files smaller

hosts file becomes 148 KB -> 116 KB

You can also stack 9 hosts for each line on Windows which will make it even smaller but harder to read

116 KB -> 102 KB

I think you can at least separately provide such files if you can't change the main ones. It may provide better performance, lower memory usage etc.

**Comment by ZeroDot1** [comment]
`shrink-service.it` https://www.virustotal.com/de/file/596930e7b0072e6304fc71a5d40f99479b80a1b10aca504cc6a9d4931bba69f2/analysis/ https://www.virustotal.com/de/domain/shrink-service.it/information/

**Comment by shdyy** [comment]
I haven't checked the addresses in my third comment, only that they provide some service which may be using or have used a miner on top.

So does shrink-service.it use a different host for the miner which can be blocked easily or is it on the same host?

Have you considered making a distinction between pure miner hosts and others which provide a service such as file download, video streaming, link shortening etc. and uses a miner? If the miner can be blocked without affecting the service, then there is no issue, if it's on the exact same host and can't be blocked separately then these should be grouped separately from the list since they would still work on-demand, it may not have an alternative and user would most likely accept the trade-off of a short duration of mining to get the file, link etc. they need

**Comment by ZeroDot1** [comment]
Yes, I am aware that it is possible to make the files smaller, but then they cannot be managed as easily anymore, and it is also not as good because of my visual impairment, so I keep it as simple as possible.
I'm currently working on a bug fix update, your contributions are very helpful. 
The Tor2Web sites are listed because malware is very often spread over these sites, and miners have already been detected, so they remain listed in the lists for the time being.  I don't know if the miner is directly on the host, it is only listed in Virustotal so that there is a miner there, so I added the page.
I have thought about separating the service pages with mine from the rest, but this way the protection from minern can't work 100%, so it's up to you which hosts you put on the white list.

**Comment by shdyy** [comment]
Blocking Tor2Web would be like blocking all .com domains. I don't think there are too many miner addresses on Tor so it should be easy to block them individually just like any other hosts. You can't block them by blocking the main domain of a Tor2Web service. They are reached over subdomains, so that's the only way to block them.

**Comment by shdyy** [comment]
In my opinion you should try to strictly block only the miner hosts.

Assume that google started mining on their pages and you could block it by adding miner.google.com

Would you block google.com too or would you go for the miner instead?

You should use the same logic if possible

**Comment by ZeroDot1** [comment]
Yes that's right, I'll remove the domains in one of the next updates. 
I would always just block the Miner all other does make not sense.

**Comment by shdyy** [comment]
Good to hear.

Another example is goodolddownloads.com

In the past they used mining as a donation method. You were not forced into it, it was voluntary so there was no reason to block it.

**Comment by ZeroDot1** [comment]
Yes, I have also removed the domain from the lists.
See: https://github.com/ZeroDot1/CoinBlockerLists/issues/133

**Comment by shdyy** [comment]
Yes, I saw that.

fitgirl also has donation by mining so it should not be blocked in future

http://fitgirl-repacks.site/donate-by-mining/

**Comment by ZeroDot1** [comment]
Yes, I can put the domain on the white list, if there is a subdomain for mining only the subdomain is put on the list.

**Comment by ZeroDot1** [comment]
Done with the next update.
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/white_list.txt
![bildschirmfoto_2018-04-15_14-24-48](https://user-images.githubusercontent.com/28985171/38778355-db2b13bc-40b8-11e8-997d-9d205a6a56d9.png)

**Comment by shdyy** [comment]
What does the white list do? This address isn't in the blacklist currently, I just said it shouldn't be added in the future since it only works voluntarily

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/135#issuecomment-381391103
List of subdomains:
```
www.rapidvideo.com
api.rapidvideo.com
control.rapidvideo.com
dev.rapidvideo.com
img.rapidvideo.com
s1.rapidvideo.com
s2.rapidvideo.com
s3.rapidvideo.com
s4.rapidvideo.com
s5.rapidvideo.com
stor1.rapidvideo.com
stream.rapidvideo.com
u1.rapidvideo.com
u2.rapidvideo.com
u3.rapidvideo.com
u4.rapidvideo.com
u5.rapidvideo.com
u6.rapidvideo.com
u7.rapidvideo.com
upload.rapidvideo.com
www1.rapidvideo.com
www2.rapidvideo.com

```

**Comment by shdyy** [comment]
Do you check for only subdomains? I find the miners by checking my DNS logs after visiting the page, and many miners are on external addresses

**Comment by ZeroDot1** [comment]
The white list is an additional list to easily add pages to the white list that are mistakenly blacklisted, the white list also contains hosts that by default belong to the white list like the domain in your example. 
I'll check every subdmain separately to be sure.
Of course this only works if I collect a list of all known subdomains.

**Comment by ZeroDot1** [comment]
One update is done, with the next update I will add the new URLs.
See: https://github.com/ZeroDot1/CoinBlockerLists/commit/54972454d003fcc8fecf73e5d3780792c2757aa7

**Comment by shdyy** [comment]
I was wondering, do you strictly try to block the host of the script itself?

For example play.video.estream.nu contains the script but if you block these two addresses, the mining is still blocked:

s2.video.estream.nu
s3.video.estream.nu

Similarly video.streaming.estream.to contains the script, but blocking these addresses blocks the mining:

m1.streaming.estream.to
m2.streaming.estream.to

In rare cases the CPU usage doesn't stop but mining itself probably is blocked: streamplay.to

I'm mentioning this in case the miner script is on the main host or on a host that is also necessary to use the service itself but if the script connects to different hosts, you can probably block the mining without blocking the service or the script

**Comment by ZeroDot1** [comment]
I divide it into different updates, as it is better to edit.
It's not so easy for me because of my visual impairment.
I hope it's not too bad that I'm doing this a little bit differently. 
I just want to try to block the subdomains with mining scripts if possible, for some it doesn't work, for example: safelinkconverter.com 
I don't use these streaming sites, but if I notice something, or I get a hint I block it of course.

**Comment by ZeroDot1** [comment]
Here is the list of mining hosts for the next update, I checked them all. 
```bash
s2.video.estream.nu
s3.video.estream.nu
m1.streaming.estream.to
m2.streaming.estream.to
m1.stream.vidzi.tv
m2.stream.vidzi.tv
p1.assetscdn.stream
p2.assetscdn.stream
p3.assetscdn.stream
p1.interestingz.pw
p2.interestingz.pw
p3.interestingz.pw
s1.vidtod.me
s2.vidtod.me
s3.vidtod.me
ws01cn.streamplay.to
ws02cn.streamplay.to
ws03cn.streamplay.to
```

**Comment by ZeroDot1** [comment]
Yes, I will remove the main pages and add the missing ones.
Most of them are actually already in the list, I always check the list for duplicate entries, so there are no mistakes with duplicates.

**Comment by shdyy** [comment]
oload.info another one to reconsider

**Comment by ZeroDot1** [comment]
I see the following subdomains: 
www.oload.info
tt1.oload.info
tt2.oload.info

**Comment by shdyy** [comment]
I think it is part of openload.co which is a very popular service. My guess is that one of the ads-popups contained miner in the past

**Comment by shdyy** [comment]
urlscan result references CoinBlockerLists so it is not useful :)

**Comment by ZeroDot1** [comment]
Yes, there is no miner available anymore, I will remove it with the next update.

**Comment by ZeroDot1** [comment]
Domains that will be removed with the next update:

```bash
oload.info
stream.to
vidzi.tv
streamplay.to
estream.nu
estream.to
rapidvideo.com
vidfile.net
```

**Comment by shdyy** [comment]
I don't know who the original source of these addresses is but many if not most of Anti-WebMiner hosts are not miners but content/service providers. So I recommend checking their list completely and removing non-miner hosts and add the miners if any are found. Some examples from looking around hosts starting with k*

kinohabr.net
kissdoujin.com (18+)
kisshentai.net (18+)
kiwifarms.net
joyreactor.cc

**Comment by shdyy** [comment]
You can find many different video hosts here which you can use to test the blacklist or discover new miners

http://putlockers.fm/watch/dKo5mo4d-the-walking-dead-season-8/episode-15.html

**Comment by ZeroDot1** [comment]
The second update is finished: https://github.com/ZeroDot1/CoinBlockerLists/commit/219613d371ae5fe4ac24ade9dc27125bde84e389 
The next update will remove more False Positive URLs, but it will take some time to finish.

**Comment by ZeroDot1** [comment]
OK, I'll take a closer look, and with the next updates I'll add some things, today comes the removal of the false positives and then I have to take a break, it's not so good when I work on the computer for so long. 
At the moment I don't have reading glasses, and I have to work with the screen magnifier, which is very stressful for me.
Tomorrow we'll continue, I hope that's okay.
But now I'll complete the update with the false positives.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/31983d017cb8cdd264eb8c5978b142ac511f2838

**Comment by shdyy** [comment]
If I understand correctly NoCoin list is only blocking the scripts from addresses like gus.host 2giga.link shrink-service.it, not entire hosts

That would be the best way to go if you can't block the miner separately from the service.

I don't know if they block the miner script on streamplay.to, maybe you can add that one to UBO list?

**Comment by ZeroDot1** [comment]
The mining hosts of streamplay.to are already in the UBO list.
```
ws01cn.streamplay.to
ws02cn.streamplay.to
ws03cn.streamplay.to
```

**Comment by ZeroDot1** [comment]
gus.host contains no Miner: https://github.com/ZeroDot1/CoinBlockerLists/issues/132

**Comment by shdyy** [comment]
I know, it probably blocks the mining but it doesn't stop the CPU usage

**Comment by ZeroDot1** [comment]
I checked it, I couldn't see anything except the standard load of my CPU, see the screenshot.
![bildschirmfoto_2018-04-15_18-44-59](https://user-images.githubusercontent.com/28985171/38780880-92361150-40dd-11e8-8edb-2d1eb129c3ba.png)

**Comment by shdyy** [comment]
it happens on the video watching screen and CPU usage isn't always high, it perodically goes maximum then zero while querying mining servers in the background every few seconds

**Comment by ZeroDot1** [comment]
OK, here's an example page, with source code, but I'll check it tomorrow.   https://hastebin.com/agujijimax.xml
https://streamplay.to/0at43i8jp9h8

**Comment by shdyy** [comment]
I think you could merge useful filters from these sources:

https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt
https://github.com/hoshsadiq/adblock-nocoin-list

But neither of them have a filter for streamplay.to yet
