### ISSUE TITLE
Why is *.bitfinex.com listed?

### ISSUE THREAD

**Issue by kar** [ZeroDot1/CoinBlockerLists#137]
I can see several *.bitfinex.com entries in the list. It's just an exchange, why is it listed?

**Comment by ZeroDot1** [comment]
A future update will move the page to the optional list.

**Comment by ZeroDot1** [comment]
@kar Sorry I haven't worked on the problem yet, I'll do it now. Unfortunately I did not have the possibility to do this due to a broken hard disk.

**Comment by ZeroDot1** [comment]
List of URLs:
```
bitfinex.com
api.bitfinex.com
api2.bitfinex.com
beta.bitfinex.com
blog.bitfinex.com
community.bitfinex.com
docs.bitfinex.com
helpdesk.bitfinex.com
helpdesk2.bitfinex.com
iota.bitfinex.com
nostalgia.bitfinex.com
support.bitfinex.com
wiki.bitfinex.com
ws.bitfinex.com
www.bitfinex.com
```

**Comment by ZeroDot1** [comment]
@kar Sorry it took a little longer, the update is now ready.
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/cf074254e4b463c5726e40529d74b176cf103e34
