### ISSUE TITLE
Add Amazon Ads

### ISSUE THREAD

**Issue by ZeroDot1** [ZeroDot1/CoinBlockerLists#138]
Since there are very few donations now I decided to include Amazon advertising in the site. 

@dnmTX What do you think it is so OK, or do I have to change something? 
https://zerodot1.github.io/CoinBlockerListsWeb/

**Comment by dnmTX** [comment]
@ZeroDot1  sorry to hear about your hard drive problems,looks like you are up and running again so i'll assume that you worked things out(let me know if i can help with anything).About the site,that blue-ish font is hard to read,not sure what was before but it was better for reading.I don't see any advertisement at the moment,they're either blocked by the hosts file or my adblocker but hey it's your website,you do what you have to do,i'm pretty sure that you wont let some aggressive malware sneak in trough the adds so you know,every little bit helps.

**Comment by ZeroDot1** [comment]
I changed the link color back to green. 
The links only turn blue if they point with the cursor on them, so you can see better which link you just clicking.

**Comment by ZeroDot1** [comment]
@dnmTX I got a new hard drive, now I can work better again. Through the advertising on the CoinBlockerLists homepage I have not yet made any income.
