### ISSUE TITLE
[Dead-Hosts] INVALID domains

### ISSUE THREAD

**Issue by funilrys** [ZeroDot1/CoinBlockerLists#139]
Hello @ZeroDot1,

First, I just wanted to inform you that your list has been added to [Dead-Hosts](https://github.com/dead-hosts) for daily testing through [CoinBlockersLists_git_ZeroDot1](https://github.com/dead-hosts/CoinBlockersLists_git_ZeroDot1). 

I sent you an invitation for joining the organization. You're not obliged to accept, I just sent you the invitation as I do consider the previously mentioned repository as yours. Indeed I only provide the infrastructure but as every generated line comes from your list, I do consider the repository as yours.
Please let me know if you want to get an automated ping when the results are available.

Anyway, back to the object of this issue, please find [here](https://github.com/dead-hosts/CoinBlockersLists_git_ZeroDot1/blob/34bc22477984f1b494d91896f1e336231d73a85c/output/domains/INVALID/list#L4-L6) the list of INVALID domains caught by [PyFunceble](https://github.com/funilrys/PyFunceble).

# About `lọgrhythm.com`

This domain has been marked as `INVALID` because it should be in [PunyCode/IDNA](https://en.wikipedia.org/wiki/Punycode) format.

# About `Free4Faucet.com`

This domain has been marked as `INVALID` because it should be in lowercase.

# About `play.video.estream.nu/`

This domain has been marked as `INVALID` because of the trailing `/`.

Have a nice day/night.

Cheers,
Nissar

**Comment by ZeroDot1** [comment]
@funilrys Thank you for reporting problems with the invalid hosts, I fixed them with the following update: https://github.com/ZeroDot1/CoinBlockerLists/commit/208556f01d5b968ca0c1a2a85bf857d5516556b3

**Comment by ZeroDot1** [comment]
@funilrys Is it possible that you can let me know when you find new invalid URLs?

**Comment by funilrys** [comment]
Hi @ZeroDot1 will do! 

P.S: If https://github.com/dead-hosts/CoinBlockersLists_git_ZeroDot1/blob/master/output/domains/INVALID/list return 404 then there is no new invalid domains. Will change your repo to run tests everyday but be aware of the generation date (for example [here](https://github.com/dead-hosts/CoinBlockersLists_git_ZeroDot1/blob/2b76dc3001276f8435df3457eb12e90a431555d0/output/domains/INVALID/list#L2)) :smile_cat:

**Comment by ZeroDot1** [comment]
@funilrys Thank you very much.
