### ISSUE TITLE
Move to Gitlab!

### ISSUE THREAD

**Issue by ZeroDot1** [ZeroDot1/CoinBlockerLists#140]
Since github is now going to Microsoft, I will move to Gitlab in the near future.
I don't like Microsoft very much, and if Github belongs to Microsoft I can't be sure if and how long Github will still exist.
Github is actually a great platform, but I don't want to take the step to Microsoft.

https://about.gitlab.com/2018/06/03/movingtogitlab/

**Comment by dnmTX** [comment]
@StevenBlack can i hear your thoughts on the subject and plans for the feature,i would really like to have  the @ZeroDot1 's lists integrated to yours instead of fetching it separately.Thanks.

**Comment by Marfjeh** [comment]
I have no idea what they are going to with github. They killed their own github site few months ago. (i forgot the name) but its probably going to end up like skype.

i already switched to gitlab.

**Comment by ZeroDot1** [comment]
I'm still in the process of switching to Gitlab, at the moment there are some problems, e.g. the imports hang in an endless loop.

**Comment by Marfjeh** [comment]
Currently the imports are having a massive hit from users switching to gitlab. its going to take a while. even my repos are still importing.

**Comment by ZeroDot1** [comment]
I can already access the files and edit and update them, but the rest of Gitlab is not working yet.
I think in a few hours at the latest in a few days it will surely work again completely.

**Comment by dnmTX** [comment]
@ZeroDot1  please update us on the progress(new URL's etc.) and if you can inform everyone that uses your lists.Thanks bud. 👍

**Comment by ZeroDot1** [comment]
@dnmTX I think it won't be a problem to change a URL as soon as the move is finished, but I can't say at the moment if everything works the way I want it to. 

I'll let everyone know about the changes as soon as it's done.

**Comment by ZeroDot1** [comment]
For all users of GithubDesktop I recommend the use of GitKraken.
https://www.gitkraken.com/git-client

**Comment by dnmTX** [comment]
@ZeroDot1  on another note,i saw that AdGuard added you(i'm using AdGuard myself) and i have this(https://github.com/hoshsadiq/adblock-nocoin-list/) filter there(just in case).In your opinion,now that i'm using your hosts lists,do i need to keep that filter,does it have something that your lists doesn't? I'm just trying to lighten up where i can.

**Comment by StevenBlack** [comment]
@dnmTX the repo is already there:  https://gitlab.com/StevenBlack/hosts

It's in mirror mode, for now.  We'll see.

I will move all my private work to Gitlab shortly.  I'm a subscriber 😄

**Comment by dnmTX** [comment]
@StevenBlack  i'd expect if you move the whole repo there and seize operations here to let us know.Thank you 👍 
@ZeroDot1  i'm using your browser based lists(on my router's dnsmasq),AdGuard is the whole program not the extension only,basically what you saying is that your browser based list is enough no need for additional one wright?

**Comment by ZeroDot1** [comment]
@dnmTX I recommend the following list, as it contains the most URLs, and provides the best protection: 
Lists: https://zerodot1.github.io/CoinBlockerLists/list.txt
Hosts: https://zerodot1.github.io/CoinBlockerLists/hosts 

All other lists are not necessary.

**Comment by dnmTX** [comment]
@ZeroDot1  it's whatever @StevenBlack is fetching from you,cause i'm using his lists(better and stronger protection this way),assuming it's the browser based one.Any recommendations needs to go to him.

**Comment by StevenBlack** [comment]
@ZeroDot1 @dnmTX for interest sake, I was watching this preparing to pop some (virtual) champagne here at the office because of the 9,500-star milestone.

Yesterday this stood at 9,493.  It's 9,479 now.  And since yesterday, my feed reports about 10 new stars.  So total drop is 24, or 0.2%.  

![2018-06-04_16-40-45](https://user-images.githubusercontent.com/80144/40940899-382122a2-6817-11e8-9e2f-e736f90709b5.jpg)

It's a stretch to extrapolate this, but 0.2% of 28 million developers is 56,000 developers.

My guess is all of Facebook, all of Google, and all of Amazon will eventually leave...

**Comment by StevenBlack** [comment]
@ZeroDot1 @dnmTX also, 0.2% of $7.5 billion is $15 million.  So at the outset Github is shedding maybe $30 million per day right now.

But this is all suspect math based on a small sample from a reasonable pool (9,500 users).

**Comment by dnmTX** [comment]
@StevenBlack  it's a sinking ship,whatever Microsoft touches turns into dust....eventually.You guys just keep up with the updates on how the moving goes.....please.

**Comment by ZeroDot1** [comment]
![bildschirmfoto vom 2018-06-04 23-02-25](https://user-images.githubusercontent.com/28985171/40941544-6f6acb6c-684b-11e8-9b71-b172f935c32d.png)

**Comment by ZeroDot1** [comment]
https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html The homepage is online :)

**Comment by ZeroDot1** [comment]
https://gitlab.com/gitlab-com/infrastructure/issues/4314

**Comment by dnmTX** [comment]
@StevenBlack is it possible(on your end) when all the hosts lists are arranged into one a line to be inserted at the beginning and the end of each individual lists.For example:
**# KADhosts Start**
domain.com
domain.com
domain.com
**# KADhosts End**
It would really help me remove things that i don't need(as we discussed yesterday with you),i managed to do it now but if you change the arrangement it will be a mess on my end

**Comment by ZeroDot1** [comment]
The files are now all online, but the import is not yet complete, it is still in the endless loop. I'll start updating as soon as possible.
I will publish as soon as everything is updated a list with all new URLs.

**Comment by ZeroDot1** [comment]
The move is finished, check out the following link there you can find all important URLs.
https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/1
