### ISSUE TITLE
[blocked] streamplay.me|streamplay.to

### ISSUE THREAD

**Issue by dnmTX** [ZeroDot1/CoinBlockerLists#141]
@ZeroDot1  it's a site hosting video files....mostly,i'm using it sometimes to stream some tv shows or whatever.If there is a miner there i think it's better to look deeper and  find it instead of blocking the entire domain.Let me hear your thoughts brother.

P.S. Don't whitelist it unless you sure though.

**Comment by ZeroDot1** [comment]
@dnmTX Please open a new report: https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/new
