### ISSUE TITLE
Add wally3k.github.io list to your "CoinBlockerLists is available at"

### ISSUE THREAD

**Issue by beerisgood** [ZeroDot1/CoinBlockerLists#26]
Your great list is added to the big PiHole list!
https://github.com/WaLLy3K/wally3k.github.io/issues/5#issuecomment-341359328

Keep up the great work

**Comment by ZeroDot1** [comment]
@beerisgood , @WaLLy3K , Thank you very much:)

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/309af0ee46a68fe81408c58dc48955b1af4713a1
