### ISSUE TITLE
some false calls / invalid hosts (pr0gramm.com)

### ISSUE THREAD

**Issue by notracking** [ZeroDot1/CoinBlockerLists#50]
Hi there,

Please have a look at the following hosts:

**false calls:**
```
www.pr0gramm.com
pr0gramm.com
thumb.pr0gramm.com
vid.pr0gramm.com
img.pr0gramm.com
```

**invalid hosts:**
```
hans.pr0gramm.com
hurensohn.pr0gramm.com
m.pr0gramm.com
```

**Comment by ZeroDot1** [comment]
@notracking Thank you for the information, I will create a list of invalid addresses.

**Comment by ZeroDot1** [comment]
https://www.virustotal.com/de/domain/pr0gramm.com/information/

**Comment by notracking** [comment]
pr0gramm.com has a client miner, but it will only start if the user clicks on a obvious bitcoint styled button, see https://www.pr0gramm.com/
The user will then be forwarded to a separate hostnames, namely: miner.pr0gramm.com, therefor only that hostname should be blocked, this will keep the website functional.

**Comment by shawly** [comment]
Why is this closed? This is still an issue!

**Comment by ZeroDot1** [comment]
@Fusl @dnmTX I'm going to take a closer look at the problem now and fix it.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/47d8e2253eeba1598277d5f7ddde3e09fe65a097
The problem is fixed, if there are any other bugs please report it.
