### ISSUE TITLE
Host to add

### ISSUE THREAD

**Issue by notracking** [ZeroDot1/CoinBlockerLists#51]
Something to check:

`api.inwemo.com` / `inwemo.com`

**Comment by ZeroDot1** [comment]
@notracking 
`api.inwemo.com` is part of the optional list, I'll update the list soon, thanks for reporting.

**Comment by ZeroDot1** [comment]
```
inwemo.com
www.inwemo.com
api.inwemo.com
cdn.inwemo.com
cdn2.inwemo.com
dashboard.inwemo.com
ftp.inwemo.com
```

**Comment by ZeroDot1** [comment]
@notracking  
Sorry, I can't work on the project at the moment, because I have problems with my internet connection.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/cde17eca3bc1a03ccd735c6a1b88ec398fcb86ae
