### ISSUE TITLE
Remove *.authedmine.com

### ISSUE THREAD

**Issue by Leseratte10** [ZeroDot1/CoinBlockerLists#52]
Can you remove all the *.authedmine.com pages from the blacklist(s)?

All the scripts hosted on the authedmine.com domain ask the user for permission before mining. These can be used for legitimate web pages instead of ads, but only if the user agrees. Scripts on that domain do not give a malicious website user the ability to mine without consent of the visitor. 

Plus, the scripts on authedmine.com provide an ability to use this mining as a captcha, forcing a browser to create a proof-of-work instead of forcing the user to enter weird characters. This useful thing is also unnecessarily blocked by these lists. 

Visit https://authedmine.com/ for an explaination.

**Comment by ZeroDot1** [comment]
CoinBlockerLists is designed to block mining in networks, it is a utility for administrators who want to prevent mining in their networks, so hosts are not removed, sorry.
