### ISSUE TITLE
Create a list for administrators

### ISSUE THREAD

**Issue by ZeroDot1** [ZeroDot1/CoinBlockerLists#7]
The list contains all mining domains to block them in different networks to protect networks and users from mining.

**Comment by ZeroDot1** [comment]
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/b7f65b45760c2e2b8e016bf7497fc4dc69b65d4b

**Comment by SMed79** [comment]
Add `inwemo.com` to the admin list.
