### ISSUE TITLE
CoinBlockerLists added to FireHOL IP Lists

### ISSUE THREAD

**Issue by ktsaou** [ZeroDot1/CoinBlockerLists#72]
Hi,

nice work!

I have added your hosts and IP feed to FireHOL IP Lists:

- http://iplists.firehol.org/?ipset=coinbl_hosts
- http://iplists.firehol.org/?ipset=coinbl_hosts_optional
- http://iplists.firehol.org/?ipset=coinbl_hosts_browser
- http://iplists.firehol.org/?ipset=coinbl_ips

There are a few interesting findings:

A good part of your lists overlap with attacks and malware ! (check the overlaps section, near the end of each page).

**Comment by ZeroDot1** [comment]
Thank you for adding the lists.
I added it to Readme, See https://github.com/ZeroDot1/CoinBlockerLists/commit/f535c6ca61698f827f57677e86bdd9d98f1e9846 .
