### ISSUE TITLE
Non GitHub links for HostMan compatibility

### ISSUE THREAD

**Issue by dnmTX** [ZeroDot1/CoinBlockerLists#92]
Any chance to provide non Github links to your lists so to be compatible with HostMan? I personally use your browser list(Huge Thanks for it) and StevenBlack's(https://github.com/StevenBlack/hosts) .For some reason HostMan doesn't like Github links and it won't update.The issue was discussed some time ago in StebenBlack's repo so now he is offering them for convenience.For Windows HostMan is probably the best hosts updater/editor etc. and with small footprint compare to others which are missing some of the features.Hopefully you can make it work.Thanks

**Comment by ZeroDot1** [comment]
@dnmTX 
Yes, I am aware of the problem, there are no alternative URLs at the moment.
http://www.sordum.org/8266/bluelifehosts-editor-v1-2/

**Comment by dnmTX** [comment]
As long as you are aware means that things might change so i'll keep an eye for any changes.Again...great job,keep it up. I'll close this as resolved.
