### ISSUE TITLE
hosts_browser: coinbase

### ISSUE THREAD

**Issue by notracking** [ZeroDot1/CoinBlockerLists#93]
Hi there,

I think all *.coinbase.com entries do not belong in the browser miner list, it's merely an exchange for crypto.

**Comment by ZeroDot1** [comment]
@notracking Thanks for the tip, it was an mistake.
With the next update the problem is fixed.

**Comment by ZeroDot1** [comment]
@notracking 
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/43a40a6c738edb662dd18595f1d5e5e4da84f297
