### ISSUE TITLE
Another false call

### ISSUE THREAD

**Issue by notracking** [ZeroDot1/CoinBlockerLists#94]
Hi,

One of my users submitted the following item on your list: netlify.com
See, https://github.com/notracking/hosts-blocklists/issues/31

**Comment by ZeroDot1** [comment]
@notracking 
Thank you very much for the information.
The next update fixes the problem.

**Comment by notracking** [comment]
No problem, glad to be able to help!

**Comment by ZeroDot1** [comment]
@notracking 
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/a39d33dd794a2bdbffb24b56b18b22d8b7c1a535
