### ISSUE TITLE
Location of smokingwheels lists on Github.

### ISSUE THREAD

**Issue by smokingwheels** [ZeroDot1/CoinBlockerLists#95]
If you would like to add or change the link on your [web page](https://zerodot1.github.io/CoinBlockerLists/) to [https://smokingwheels.github.io/Pi-hole/](https://smokingwheels.github.io/Pi-hole/)  it has a text format to copy and paste into a Pi-hole blocklist or wget command.  

Thanks.

Try adding a blank CR on each of the References:

**Comment by ZeroDot1** [comment]
I have changed the URL to: https://smokingwheels.github.io/Pi-hole/allhosts .
With the next update it will be uploaded.
![bildschirmfoto_2018-01-07_18-01-42](https://user-images.githubusercontent.com/28985171/34651755-db8b1dd8-f3d4-11e7-9bb7-8d4cc4d22c88.png)

**Comment by ZeroDot1** [comment]
@smokingwheels 
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/f5300ca063272a93bdcc5d527acbe79a50ffc17d
