### ISSUE TITLE
The list which contains all IPs contains invalid IP address

### ISSUE THREAD

**Issue by Gareze** [ZeroDot1/CoinBlockerLists#96]
Hi,

just wanted to make you aware that the download list for IPs contains and invalid IP address '27.148.157[.]89'

Thanks 

G

**Comment by ZeroDot1** [comment]
@Gareze 
https://www.virustotal.com/de/ip-address/27.148.157.89/information/

**Comment by HappyGuy22** [comment]
@Gareze is telling that there's a typo 27.148.157[.]89 which contains bracket [ ], @ZeroDot1 can you review it?

**Comment by ZeroDot1** [comment]
I have checked it, it's not a invalid IP address

**Comment by ZeroDot1** [comment]
@Gareze @HappyGuy22 Thanks for the bug report. https://github.com/ZeroDot1/CoinBlockerLists/commit/c6b2b489bba06144c6a752ffff3abe0bccf65e25
