### ISSUE TITLE
Inappropriate entry in MiningServerIPList.txt

### ISSUE THREAD

**Issue by mazesy** [ZeroDot1/CoinBlockerLists#98]
Hi,

Thanks for your CoinBlockerLists.

I noticed one entry in your _MiningServerIPList.txt_ Last modified: 20 01 2018 16:44 which is of course inappropriate : 04.27.157.60

Is this a typo mistake (??4.27.157.60) or should the address simply be removed?
Thanks.

**Comment by ZeroDot1** [comment]
@mazesy 
Oh, thank you, I've lost a number. 104.27.157.60
With the next update the bug is fixed, thanks for the information.

**Comment by ZeroDot1** [comment]
@mazesy 
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/d6de96dcb780c699dbb831250cb0b70c3176f587
