### ISSUE TITLE
Redundant entries in hosts files, with and without 0.0.0.0

### ISSUE THREAD

**Issue by mazesy** [ZeroDot1/CoinBlockerLists#99]
Hi,

**moneropool.phoenix.dj** in _hosts_browser[.txt_] Last modified: 24 01 2018 14:24
**www.cointraffic.io** in _hosts_optional[.txt]_ Last modified: 20 01 2018 16:44

each appear twice in their respective file, with and without 0.0.0.0

I admit that I have no idea of the effect of a url free of its address in a hosts file, maybe of no importance but in case I mention it ...

**Comment by ZeroDot1** [comment]
Hey, thanks for the information.
I have a visual impairment, and I just didn't see it, sorry. 
I'll fix that right now.

**Comment by ZeroDot1** [comment]
@mazesy Thank you very much.
Done! : https://github.com/ZeroDot1/CoinBlockerLists/commit/524b6ff713f4f9d0af8e4a32110a9bef9568006b

**Comment by mazesy** [comment]
@ZeroDot1 you're the one to be thanked, I really appreciate your CoinBlockerLists and i'm not the only one (in fact I got here by someone who mentioned your lists on Ghacks).
Nice work.
